#!/bin/bash
echo "⚠️  ATENÇÃO: Este script não pode mais reverter a reorganização!"
echo "📁 A estrutura antiga foi removida para limpeza."
echo "✅ A nova estrutura em 'checkin_jump/' está funcionando corretamente."
echo ""
echo "🎯 Para continuar trabalhando:"
echo "   cd checkin_jump"
echo "   python manage.py runserver"
echo ""
echo "🚀 Para fazer deploy no Render, siga as instruções em:"
echo "   checkin_jump/README_DEPLOY.md" 