# Generated by Django 5.2 on 2025-07-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0007_pequenogrupo_alter_adolescente_pg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imperio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
