# Generated by Django 5.2 on 2025-07-02 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0008_imperio'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescente',
            name='imperio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adolescentes.imperio'),
        ),
    ]
