# Generated by Django 5.2 on 2025-07-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0009_adolescente_imperio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adolescente',
            options={'permissions': [('view_dashboard', 'Pode visualizar o dashboard')]},
        ),
    ]
