# Generated by Django 5.2 on 2025-08-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0010_alter_adolescente_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pequenogrupo',
            old_name='lider',
            new_name='genero_pg',
        ),
    ]
