# Generated by Django 5.2 on 2025-08-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0011_rename_lider_pequenogrupo_genero_pg'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaevento',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título da celebração (ex: 40 Dias de Generosidade)', max_length=200, null=True),
        ),
    ]
