# Generated by Django 5.2 on 2025-08-12 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0013_contagemauditorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContagemVisitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_visitantes', models.PositiveIntegerField(help_text='Número de visitantes no dia')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contagens_visitantes', to='adolescentes.diaevento')),
                ('usuario_registro', models.ForeignKey(help_text='Usuário que fez o registro', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contagem de Visitantes',
                'verbose_name_plural': 'Contagens de Visitantes',
                'ordering': ['-data_registro'],
                'unique_together': {('dia',)},
            },
        ),
    ]
