# Generated by Django 5.2 on 2025-08-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0015_add_fk_pg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adolescente',
            options={'permissions': [('view_dashboard', 'Pode visualizar o dashboard'), ('view_pgs_page', 'Pode ver página de PGs')]},
        ),
    ]
