# Generated by Django 5.2 on 2025-08-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0017_enable_pg_trgm_and_trgm_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adolescente',
            options={'permissions': [('view_dashboard', 'Pode visualizar o dashboard'), ('view_pgs_page', 'Pode ver página de PGs'), ('review_duplicates', 'Pode revisar e mesclar duplicados')]},
        ),
    ]
