# Generated by Django 5.2 on 2025-08-15 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0018_alter_adolescente_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicadoRejeitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('adolescente_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejeicoes_como_a', to='adolescentes.adolescente')),
                ('adolescente_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejeicoes_como_b', to='adolescentes.adolescente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('adolescente_a', 'adolescente_b')},
            },
        ),
    ]
