# Generated by Django 5.2 on 2025-08-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0019_duplicadorejeitado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenca',
            options={'ordering': ['-dia', 'adolescente']},
        ),
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together={('adolescente', 'dia')},
        ),
        migrations.AddIndex(
            model_name='presenca',
            index=models.Index(fields=['adolescente', 'dia'], name='adolescente_adolesc_2bfdde_idx'),
        ),
        migrations.AddIndex(
            model_name='presenca',
            index=models.Index(fields=['dia', 'presente'], name='adolescente_dia_id_20358f_idx'),
        ),
        migrations.AddIndex(
            model_name='presenca',
            index=models.Index(fields=['adolescente', 'presente'], name='adolescente_adolesc_085aa8_idx'),
        ),
    ]
