# Generated by Django 5.2 on 2026-02-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0020_optimize_presenca_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaevento',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='imperio',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='pequenogrupo',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='adolescente',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='adolescente',
            name='ano',
            field=models.PositiveIntegerField(db_index=True, default=2026),
        ),
        migrations.AddField(
            model_name='adolescente',
            name='nome_responsavel',
            field=models.CharField(blank=True, help_text='Nome do pai/mãe ou responsável', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adolescente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone do adolescente', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adolescente',
            name='telefone_responsavel',
            field=models.CharField(blank=True, help_text='Telefone do responsável', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diaevento',
            name='ano',
            field=models.PositiveIntegerField(db_index=True, default=2026),
        ),
        migrations.AddField(
            model_name='imperio',
            name='ano',
            field=models.PositiveIntegerField(db_index=True, default=2026),
        ),
        migrations.AddField(
            model_name='pequenogrupo',
            name='ano',
            field=models.PositiveIntegerField(db_index=True, default=2026),
        ),
        migrations.AlterField(
            model_name='diaevento',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='imperio',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='diaevento',
            unique_together={('data', 'ano')},
        ),
        migrations.AlterUniqueTogether(
            name='imperio',
            unique_together={('nome', 'ano')},
        ),
    ]
