# Generated by Django 5.2 on 2026-03-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0022_set_ano_2025_existing_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pequenogrupo',
            options={'ordering': ['ordem', 'nome']},
        ),
        migrations.AddField(
            model_name='pequenogrupo',
            name='ano_nascimento_fim',
            field=models.PositiveIntegerField(blank=True, help_text='Ano de nascimento final (ex: 2012)', null=True),
        ),
        migrations.AddField(
            model_name='pequenogrupo',
            name='ano_nascimento_inicio',
            field=models.PositiveIntegerField(blank=True, help_text='Ano de nascimento inicial (ex: 2010)', null=True),
        ),
        migrations.AddField(
            model_name='pequenogrupo',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibição (para ordenação manual)'),
        ),
    ]
