# Generated by Django 4.2.11 on 2026-04-10 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adolescentes', '0023_alter_pequenogrupo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do evento especial (ex: Conferência Jump, Retiro de Jovens)', max_length=200)),
                ('data', models.DateField(help_text='Data do evento')),
                ('ano', models.PositiveIntegerField(db_index=True, default=2026)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional do evento', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Especial',
                'verbose_name_plural': 'Eventos Especiais',
                'ordering': ['-data'],
                'unique_together': {('nome', 'data', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='VisitanteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('convidado_por', models.CharField(blank=True, help_text='Quem convidou este visitante', max_length=200, null=True)),
                ('presente', models.BooleanField(default=True, help_text='Marcou presença no evento')),
                ('migrado', models.BooleanField(default=False, help_text='Se já foi movido para a tabela de Adolescentes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('adolescente_migrado', models.ForeignKey(blank=True, help_text='Adolescente criado após migração', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adolescentes.adolescente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitantes', to='adolescentes.eventoespecial')),
            ],
            options={
                'verbose_name': 'Visitante de Evento',
                'verbose_name_plural': 'Visitantes de Eventos',
                'ordering': ['nome', 'sobrenome'],
                'indexes': [models.Index(fields=['evento', 'presente'], name='adolescente_evento__69a5e2_idx'), models.Index(fields=['migrado'], name='adolescente_migrado_983ab5_idx')],
            },
        ),
    ]
